sort by pageid?
lisps/tagfilter pull request #26
Opened 2023-06-23 12:43 UTC by fjf2002

My company had the request to sort by page id, so I made a new flag `sortbypageid`.

Any interest to include this into the master branch?

2023-08-14 12:16 UTC, fjf2002 commented
*ping* any news here?

2023-08-14 20:47 UTC, Klap-in requested changes
Looks fine, not tested yet.
Could you please fix the minor comment?

2023-08-14 20:47 UTC, Klap-in commented on helper/syntax.php
> +            'sortbypageid' => false
Please update the phpdocs as well please.

2023-08-28 07:49 UTC, fjf2002 commented
@Klap-in: Thanks for your response.
However I mostly am interested in using the include plugin to render content (instead of links), see PR #27 . Thus pagelist gets bypassed/replaced by the include plugin, and pagelist can't sort for me.

2023-09-27 10:16 UTC, fjf2002 commented
*ping* any interest to merge this?

2023-10-07 17:26 UTC, merged

2023-10-09 07:44 UTC, fjf2002 commented
Thanks a lot. Shall I document this at https://www.dokuwiki.org/plugin:tagfilter or wait until the plugin's next release ?

2023-10-09 19:03 UTC, peterfromearth commented
yes, would be great if you could update it.

2023-10-12 11:54 UTC, fjf2002 commented
> yes, would be great if you could update it.

Done. You can decide if you want to mark the pagelist plugin as optional - it should be an either-or of necessity between pagelist plugin an include plugin.